apps/dashboard/urls.py
from django.urls import path

from . import views
from apps.users.views import PasswordChangeView

app_name = 'dashboard'
urlpatterns = [
    path('', views.ProfileView.as_view(), name='profile'),
    path('devices/', views.DeviceListView.as_view(), name='devices'),
    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('bookmarks/', views.BookmarkListView.as_view(), name='bookmarks'),
]

apps/main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('recent/', views.RecentContentListView.as_view(), name='recent'),
    path('popular/', views.PopularContentListView.as_view(), name='popular'),
    path('collections/', views.CollectionListView.as_view(), name='collections'),
    path('collections/<slug:slug>/', views.CollectionContentListView.as_view(), name='collection'),
    path('genres/<genre>/', views.GenreContentListView.as_view(), name='genre'),

    path('search/', views.SearchResultListView.as_view(), name='search'),
]

apps/subscription/urls.py
from django.urls import path

from . import views

app_name = 'subscription'
urlpatterns = [
    path('', views.PlanListView.as_view(), name='plans'),
]

apps/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from django.views.generic import RedirectView

from . import views

app_name = 'users'
urlpatterns = [
    path('', RedirectView.as_view(pattern_name='users:login')),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('signup/verification/', views.SignupVerificationView.as_view(), name='signup_verification'),
    path('signup/complete/', views.SignupConfirmView.as_view(), name='signup_complete'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path(
        'password_reset/verification/',
        views.PasswordResetVerificationView.as_view(),
        name='password_reset_verification',
    ),
    path('password_reset/confirm/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('', include('apps.users.api.urls')),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.main.urls')),
    path('', include('apps.content.urls')),
    path('votes/', include('apps.votes.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('apps.users.urls')),
    path('dashboard/', include('apps.dashboard.urls')),
    path('subscription/', include('apps.subscription.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
{% load static %}
<header class="header bg-white fixed-top">
  <div class="px-3 px-sm-4 py-2 d-flex justify-content-between align-items-center">
    <div class="d-flex align-items-center">
      <a href="/" class="header-logo h-100 d-inline-block me-2">
        <picture class="d-block">
          <source media="(min-width:768px)" srcset="{% static 'global/images/logo.png' %}">
          <img src="{% static 'global/images/sm-logo.png' %}" alt="نینی لرنینگ" class="w-100">
        </picture>
      </a>
      <div class="genres d-none d-sm-block me-3">
        <ul class="mb-0 list-unstyled">
          {% for genre in genres %}
            <li><a href="{{ genre.get_absolute_url }}" style="white-space: nowrap">{{ genre.genre }}</a></li>
          {% endfor %}
        </ul>
      </div>
      <a href="{% url 'main:search' %}"
         class="search text-decoration-none text-dark d-md-flex align-items-center d-none">
        <i class="fas fa-search fa-rotate-90 align-middle" style="font-size: 1.4rem"></i>
      </a>
    </div>
    <div class="d-flex">
      <a href="{% url 'main:search' %}"
         class="search text-decoration-none text-dark me-2 d-md-none d-flex align-items-center">
        <i class="fas fa-search fa-rotate-90 align-middle" style="font-size: 1.4rem"></i>
      </a>
      {% if not user.is_vip %}
        <a href="{% url 'subscription:plans' %}" class="btn btn-primary me-1">خرید اشتراک</a>
      {% endif %}
      {% if user.is_anonymous %}
        <a href="{% url 'users:login' %}" class="btn btn-outline-primary">ورود</a>
      {% else %}
        <div class="avatar position-relative">
          <img class="w-100 rounded" src="{% static 'global/images/avatar.png' %}" alt="آواتار">
          <ul class="popup position-absolute p-2 list-unstyled rounded">
            <li>
              <a href="{% url 'dashboard:profile' %}" class="popup-item pb-2">
                <div class="user-info">
                  <span class="d-block mb-2">{{ user.get_full_name }}</span>
                  <span class="phone-number">
                    <i class="fas fa-mobile-alt"></i>
                    {{ user.phone_number }}
                  </span>
                </div>
                <span class="popup-link align-self-center">
                  تنظیمات
                  <i class="fas fa-angle-left align-middle"></i>
                </span>
              </a>
            </li>
            <li>
              <a href="{% url 'dashboard:bookmarks' %}" class="popup-item py-2">
                <i class="fas fa-bookmark align-middle"></i>
                نشان شده‌‌ها
              </a>
            </li>
            <li>
              <a href="{% url 'dashboard:devices' %}" class="popup-item py-2">
                <i class="fas fa-desktop align-middle"></i>
                دستگاه ها
              </a>
            </li>
            <li>
              <a href="{% url 'users:logout' %}?next={{ request.path }}" class="popup-item py-2">
                <i class="fas fa-sign-out-alt align-middle"></i>
                خروج
              </a>
            </li>
          </ul>
        </div>
      {% endif %}
    </div>
  </div>
  <div class="genres d-sm-none">
    <ul class="mb-0 list-unstyled overflow-auto" style="white-space: nowrap">
      {% for genre in genres %}
        <li><a href="{{ genre.get_absolute_url }}" style="white-space: nowrap">{{ genre.genre }}</a></li>
      {% endfor %}
    </ul>
  </div>
</header>

templates/includes/messages.html
{% if messages %}
  <div class="messages {{ classes }}">
    {% for message in messages %}
      <div class="message text-{{ message.tags }}">
        {{ message }}
      </div>
    {% endfor %}
  </div>
{% endif %}