apps/content/api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('bookmark/<slug:slug>/', views.BookmarkAPIView.as_view(), name='bookmark'),
]

apps/content/urls.py
from django.urls import path, include

from . import views

app_name = 'content'
urlpatterns = [
    path('serial/<slug:slug>/', views.SerialDetailView.as_view(), name='serial_detail'),
    path('movie/<slug:slug>/', views.MovieDetailView.as_view(), name='movie_detail'),
    path(
        'serial/<slug:slug>/season/<int:season_number>/episodes/',
        views.SeasonEpisodeListView.as_view(),
        name='season_episodes',
    ),
    path('', include('apps.content.api.urls')),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.main.urls')),
    path('', include('apps.content.urls')),
    path('votes/', include('apps.votes.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('apps.users.urls')),
    path('dashboard/', include('apps.dashboard.urls')),
    path('subscription/', include('apps.subscription.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/content/models.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from apps.content.managers import ContentManager, SerialManager, MovieManager
from apps.votes.models import VoteMixin


def poster_upload_path(instance, filename):
    if isinstance(instance, Serial):
        return f'series/{instance.en_name}/posters/{filename}'
    elif isinstance(instance, Episode):
        file_ext = filename.split('.')[-1]
        return f'series/{instance.serial.en_name}/episodes/poster.{file_ext}'
    elif isinstance(instance, Movie):
        return f'movies/{instance.en_name}/posters/{filename}'


def video_upload_path(instance, filename):
    if isinstance(instance, Episode):
        return 'series/{}/episodes/{}/{}'.format(
            instance.serial.en_name,
            instance.episode_number,
            filename,
        )
    elif isinstance(instance, Movie):
        return 'movies/{}/{}'.format(
            instance.en_name,
            filename,
        )


def subtitle_upload_path(instance, filename):
    if isinstance(instance, Episode):
        return 'series/{}/episodes/{}/subtitles/{}'.format(
            instance.serial.en_name,
            instance.episode_number,
            filename,
        )
    elif isinstance(instance, Movie):
        return 'movies/{}/subtitles/{}'.format(
            instance.en_name,
            filename,
        )


def video_format_validator(file):
    file_extension = file.name.split('.')[-1].lower()
    if file_extension not in settings.ALLOWED_VIDEO_FORMAT:
        raise ValidationError(
            _('Video format is invalid. the valid video formats are ') + '، '.join(
                settings.ALLOWED_VIDEO_FORMATS))


class Genre(models.Model):
    genre = models.CharField(_('genre'), max_length=50, unique=True)

    class Meta:
        verbose_name = _('genre')
        verbose_name_plural = _('genres')

    def __str__(self):
        return self.genre

    def get_absolute_url(self):
        return reverse('main:genre', kwargs={'genre': self.genre})


class Content(VoteMixin):
    class ContentTypeChoices(models.TextChoices):
        SERIAL = 'S', _('serial')
        MOVIE = 'M', _('movie')

    pe_name = models.CharField(_('persian name'), max_length=120, unique=True)
    en_name = models.CharField(_('english name'), max_length=120, unique=True)
    slug = models.SlugField(_('slug'))
    age_range = models.CharField(_('age range'), max_length=50)
    country = models.CharField(
        _('country'),
        max_length=20,
        help_text=_('Product of which country?'),
    )
    description = models.TextField(_('description'))
    small_poster = models.ImageField(_('small poster'), upload_to=poster_upload_path)
    large_poster = models.ImageField(_('large poster'), upload_to=poster_upload_path)
    duration = models.CharField(_('duration'), max_length=20)
    resolution = models.CharField(_('resolution'), max_length=20)
    suggestions = models.ManyToManyField('self', verbose_name=_('suggestions'), blank=True)
    genres = models.ManyToManyField(Genre, verbose_name=_('genre'), related_name='contents')
    content_type = models.CharField(
        _('content type'),
        choices=ContentTypeChoices.choices,
        max_length=1,
        db_index=True,
    )

    video = models.FileField(
        _('video'),
        upload_to=video_upload_path,
        validators=[video_format_validator],
        null=True
    )
    pe_subtitle = models.FileField(
        _('persian subtitle'),
        upload_to=subtitle_upload_path,
        blank=True,
        null=True,
    )
    en_subtitle = models.FileField(
        _('english subtitle'),
        upload_to=subtitle_upload_path,
        blank=True,
        null=True
    )
    is_vip = models.BooleanField(
        _('vip'),
        default=False,
    )
    created_at = models.DateTimeField(_('created date'), default=timezone.now, editable=False)

    objects = ContentManager()

    def __str__(self):
        return self.pe_name

    def get_absolute_url(self):
        if self.content_type == self.ContentTypeChoices.SERIAL:
            return reverse('content:serial_detail', kwargs={'slug': self.slug})
        elif self.content_type == self.ContentTypeChoices.MOVIE:
            return reverse('content:movie_detail', kwargs={'slug': self.slug})


class Serial(Content):
    class Meta:
        proxy = True
        verbose_name = _('serial')
        verbose_name_plural = _('series')

    objects = SerialManager()


class Season(models.Model):
    season_number = models.PositiveSmallIntegerField(verbose_name=_('season'))
    serial = models.ForeignKey(Serial, verbose_name=_('serial'), on_delete=models.CASCADE, related_name='seasons')

    class Meta:
        verbose_name = _('season')
        verbose_name_plural = _('seasons')
        unique_together = ('season_number', 'serial')

    def __str__(self):
        return '{} {} {}'.format(self.serial.pe_name, self._meta.verbose_name, self.season_number)


class Episode(VoteMixin):
    title = models.CharField(_('title'), max_length=50)
    poster = models.ImageField(_('poster'), upload_to=video_upload_path)
    video = models.FileField(_('video'), upload_to=video_upload_path, validators=[video_format_validator])
    pe_subtitle = models.FileField(_('persian subtitle'), upload_to=subtitle_upload_path, blank=True, null=True)
    en_subtitle = models.FileField(_('english subtitle'), upload_to=subtitle_upload_path, blank=True, null=True)
    episode_number = models.PositiveSmallIntegerField(default=1, verbose_name=_('episode number'))
    is_vip = models.BooleanField(_('vip'))
    season = models.ForeignKey(Season, on_delete=models.CASCADE, null=True, related_name='episodes')

    class Meta:
        verbose_name = _('episode')
        verbose_name_plural = _('episodes')
        ordering = ['episode_number']
        unique_together = ('season', 'episode_number')

    def __str__(self):
        return '{} {} {} {} {}'.format(
            self.serial.pe_name,
            self.season._meta.verbose_name,
            self.season.season_number,
            self._meta.verbose_name,
            self.episode_number,
        )

    @property
    def serial(self):
        return self.season.serial


class Movie(Content):
    class Meta:
        proxy = True
        verbose_name = _('movie')
        verbose_name_plural = _('movies')

    objects = MovieManager()

apps/content/api/views.py
from django.utils.translation import gettext_lazy as _
from rest_framework.generics import get_object_or_404
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.content.models import Content


class BookmarkAPIView(APIView):
    permission_classes = (IsAuthenticated,)

    def post(self, request, *args, **kwargs):
        self.object = get_object_or_404(Content, slug=self.kwargs.get('slug'))
        self.request.user.bookmarks.add(self.object)
        return Response({'detail': _('The object is bookmarked.')})

    def delete(self, request, *args, **kwargs):
        self.object = get_object_or_404(Content, slug=self.kwargs.get('slug'))
        self.request.user.bookmarks.remove(self.object)
        return Response({'detail': _('The object bookmark deleted.')})

apps/content/views.py
from django.contrib.contenttypes.models import ContentType
from django.db.models import Q, F
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView

from apps.content.models import Serial, Movie, Episode
from apps.votes.models import Vote


class ExtraMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'bookmarked': self.get_bookmarked(),
            'liked': self.get_liked(),
            'disliked': self.get_disliked(),
        })
        return context

    def get_bookmarked(self):
        if self.request.user.is_authenticated:
            return self.request.user.is_bookmarked(self.object)

    def get_liked(self):
        if self.request.user.is_authenticated:
            return self.object.liked(self.request.user)

    def get_disliked(self):
        if self.request.user.is_authenticated:
            return self.object.disliked(self.request.user)


class SeasonEpisodesMixin:
    def get_season_episodes(self, season):
        episodes = season.episodes.all()
        if self.request.user.is_authenticated:
            content_type = ContentType.objects.get_for_model(Episode)
            episodes = episodes.annotate(
                is_liked=Q(
                    votes__user=self.request.user,
                    votes__vote=Vote.Choices.LIKE,
                    votes__object_id=F('id'),
                    votes__content_type=content_type,
                ),
                is_disliked=Q(
                    votes__user=self.request.user,
                    votes__vote=Vote.Choices.DISLIKE,
                    votes__object_id=F('id'),
                    votes__content_type=content_type,
                ),
            )
        return episodes


class SerialDetailView(ExtraMixin, SeasonEpisodesMixin, DetailView):
    template_name = 'content/detail/serial_detail.html'
    queryset = Serial.objects.prefetch_related('genres', 'suggestions__genres')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['first_season_episodes'] = self.get_first_season_episodes()
        return context

    def get_first_season_episodes(self):
        first_season = self.object.seasons.filter(season_number=1).get()
        return self.get_season_episodes(first_season)


class SeasonEpisodeListView(SeasonEpisodesMixin, ListView):
    template_name = 'content/detail/episode_list.html'
    context_object_name = 'episodes'

    def get_queryset(self):
        serial = get_object_or_404(Serial, slug=self.kwargs.get('slug'))
        season = get_object_or_404(serial.seasons, season_number=self.kwargs.get('season_number'))
        return self.get_season_episodes(season)


class MovieDetailView(ExtraMixin, DetailView):
    template_name = 'content/detail/movie_detail.html'
    queryset = Movie.objects.prefetch_related('genres', 'suggestions__genres')

templates/content/detail/_base.html
{% extends '_base.html' %}
{% load static %}

{% block meta_title %}{{ object.pe_name }}{% endblock %}

{% block css %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/7.4.1/swiper-bundle.min.css"/>
  <link rel="stylesheet" href="{% static 'global/css/header.css' %}">
  <link rel="stylesheet" href="{% static 'content/css/detail.css' %}">
{% endblock %}

{% block content %}
  {% include 'includes/header.html' %}

  <main id="main" class="space-from-header">
    {% block content_header %}{% endblock %}

    <div class="container py-4">
      <div class="description mb-5">
        <h4 class="title mb-3 fw-bold">
          درباره {{ object.pe_name }}
        </h4>
        <p>{{ object.description }}</p>
      </div>
      {% block episodes %}{% endblock %}
      {% with suggestions=object.suggestions.all %}
        {% if suggestions %}
          <div class="suggestions p-3">
            <h4 class="suggestions-title mb-3 fw-bold">
              پیشنهادی
            </h4>
            <div class="suggestions-wrapper position-relative px-3">
              <div class="swiper">
                <div class="swiper-wrapper">
                  {% for suggestion in suggestions %}
                    <div class="suggestion mb-3">
                      {% include 'content/includes/item.html' with object=suggestion %}
                    </div>
                  {% endfor %}
                </div>
              </div>
              <div class="swiper-button-next d-none d-md-block"></div>
              <div class="swiper-button-prev d-none d-md-block"></div>
            </div>
          </div>
        {% endif %}
      {% endwith %}
    </div>
  </main>
{% endblock %}

{% block js %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/7.4.1/swiper-bundle.min.js"></script>
  <script src="{% static 'content/js/detail.js' %}"></script>
  <script src="{% static 'content/js/vote.js' %}"></script>
{% endblock %}

templates/content/detail/episode_list.html
{% for episode in episodes %}
  <div class="episode p-3 mb-3 rounded-1">
    <div class="row">
      <div class="col-5 col-sm-3 episode-poster">
        <div class="position-relative">
          {% if episode.pe_subtitle or episode_en_subtitle %}
            <div class="subtitle position-absolute rounded-pill">
              <span>زیرنویس دارد</span>
            </div>
          {% endif %}
          <img src="{{ episode.poster.url }}" alt="{{ episode.title }}" class="w-100 rounded">
        </div>
      </div>
      <div class="col-7 col-sm-9 episode-info">
        <div class="episode-title mb-3">
          <h4 class="fw-bold d-flex justify-content-between">
            <span>
              فصل {{ episode.season.season_number }} قسمت {{ episode.episode_number }}
              {% if episode.is_vip %}
                <span class="badge bg-warning ms-1">نیاز به اشتراک</span>
              {% else %}
                <span class="badge bg-success ms-1">رایگان</span>
              {% endif %}
            </span>
            <a href="" class="download d-none d-sm-inline-block">
              <i class="fas fa-cloud-download"></i>
            </a>
          </h4>
        </div>
        <p class="episode-description d-none d-sm-block mb-3">
          {{ episode.title }}
        </p>
        <div class="episode-footer d-none d-sm-flex justify-content-between">
          <div class="episode-popularity d-inline-block align-self-end">
            <i class="fas fa-thumbs-up me-1"></i>
            <span>{{ episode.popularity }}%</span>
            <span>({{ episode.total_votes|floatformat:'g' }})</span>
          </div>
          <div class="d-inline-block">
            <div class="episode-rating d-inline-block">
              <a data-url="{% url 'votes:episode_vote' episode.pk %}?vote=like" role="button"
                 class="btn like {% if episode.is_liked %}liked{% endif %}">
                <i class="fas fa-thumbs-up align-middle"></i>
              </a>
              <a data-url="{% url 'votes:episode_vote' episode.pk %}?vote=dislike" role="button"
                 class="btn dislike {% if episode.is_disliked %}disliked{% endif %}">
                <i class="fas fa-thumbs-down align-middle"></i>
              </a>
            </div>
            <a class="btn btn-primary btn-play">
              <i class="fas fa-play align-middle"></i>
              <span class="d-inline-block">
                {% if not episode.is_vip or episode.is_vip and user.is_vip %}
                  تماشا
                {% else %}
                  خرید اشتراک
                {% endif %}
              </span>
            </a>{{ a|floatformat }}
          </div>
        </div>
      </div>
    </div>
    <div class="row mt-3 d-sm-none">
      <div class="col-12">
        <p class="episode-description mb-3">
          {{ episode.title }}
        </p>
      </div>
      <div class="col">
        <div class="episode-footer d-flex justify-content-between">
          <div class="episode-popularity d-inline-block align-self-end">
            <i class="fas fa-thumbs-up me-1"></i>
            <span>{{ episode.popularity }}%</span>
            <span>({{ episode.total_votes|floatformat:'g' }})</span>
          </div>
          <div class="d-inline-block">
            <a href="" class="download btn d-inline-block">
              <i class="fas fa-cloud-download"></i>
            </a>
            <div class="episode-rating d-inline-block">
              <a data-url="{% url 'votes:episode_vote' episode.pk %}?vote=like" role="button"
                 class="btn like {% if episode.is_liked %}liked{% endif %}">
                <i class="fas fa-thumbs-up align-middle"></i>
              </a>
              <a data-url="{% url 'votes:episode_vote' episode.pk %}?vote=dislike" role="button"
                 class="btn dislike {% if episode.is_disliked %}disliked{% endif %}">
                <i class="fas fa-thumbs-down align-middle"></i>
              </a>
            </div>
            <a class="btn btn-primary btn-play">
              <i class="fas fa-play align-middle"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endfor %}

templates/content/detail/movie_detail.html
{% extends 'content/detail/_base.html' %}

{% block content_header %}
  {% include 'content/includes/header.html' %}
{% endblock %}

templates/content/detail/serial_detail.html
{% extends 'content/detail/_base.html' %}
{% load utils %}

{% block content_header %}
  {% include 'content/includes/header.html' %}
{% endblock %}

{% block episodes %}
  <div class="episodes">
    <h4 class="title mb-4">قسمت‌های {{ object.pe_name }}</h4>
    <div class="seasons">
      <ul class="mb-0 pb-3 list-unstyled d-flex overflow-auto w-100" style="white-space: nowrap">
        {% for season in object.seasons.all %}
          <li class="btn btn-outline-primary rounded season me-3{% if season.season_number == 1 %} selected-season{% endif %}">
            <a role="button" class="text-decoration-none"
               data-url="{% url 'content:season_episodes' object.slug season.season_number %}">
              فصل {{ season.season_number|digit_to_word }}
            </a>
          </li>
        {% endfor %}
      </ul>
      <div class="episodes-count-wrapper text-center mb-3 position-relative">
        <span class="px-3">
          <span class="episodes-count"></span>
          قسمت
        </span>
      </div>
    </div>
    <div class="episodes-wrapper position-relative">
      <div class="loading" style="display: none">
        <span class="spinner"></span>
      </div>
      <div class="episodes-container">
        {% include 'content/detail/episode_list.html' with episodes=first_season_episodes %}
      </div>
    </div>
  </div>
{% endblock %}