apps/dashboard/urls.py
from django.urls import path

from . import views
from apps.users.views import PasswordChangeView

app_name = 'dashboard'
urlpatterns = [
    path('', views.ProfileView.as_view(), name='profile'),
    path('devices/', views.DeviceListView.as_view(), name='devices'),
    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('bookmarks/', views.BookmarkListView.as_view(), name='bookmarks'),
]

apps/subscription/urls.py
from django.urls import path

from . import views

app_name = 'subscription'
urlpatterns = [
    path('', views.PlanListView.as_view(), name='plans'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.main.urls')),
    path('', include('apps.content.urls')),
    path('votes/', include('apps.votes.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('apps.users.urls')),
    path('dashboard/', include('apps.dashboard.urls')),
    path('subscription/', include('apps.subscription.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/dashboard/models.py
from django.db import models

# Create your models here.

apps/users/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _

from apps.core import otp
from .models import User

UserModel = get_user_model()


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'autofocus': True}),
        validators=(User.phone_number_validator,)
    )
    error_messages = {
        'invalid_login': _(
            'Any user with this %(username)s and password not found. Note that password '
            'may be case-sensitive.'
        ),
        'inactive': _('This account is inactive.'),
    }


class SignupForm(forms.Form):
    phone_number = forms.CharField(
        label=_('Phone number'),
        widget=forms.TextInput(),
        validators=(User.phone_number_validator,),
    )

    def clean(self):
        user, created = UserModel.objects.get_or_create(
            phone_number=self.cleaned_data['phone_number'],
            defaults={
                'is_active': False,
            }
        )
        # user with this phone number already signed up
        if user.is_active:
            self.add_error('phone_number', _('A user with this phone number already exist.'))
        else:
            self.cleaned_data['user'] = user

        return self.cleaned_data

    def save(self):
        return self.cleaned_data['user']


class SignupCompleteForm(forms.Form):
    first_name = forms.CharField(label=_('First name'))
    last_name = forms.CharField(label=_('Last name'))
    password = forms.CharField(
        label=_('Password'),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        help_text=password_validation.password_validators_help_text_html(),
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean(self):
        # need to save user info for validating password
        first_name = self.cleaned_data['first_name']
        last_name = self.cleaned_data['last_name']
        password = self.cleaned_data['password']

        if first_name and last_name and password:
            self.user.first_name = first_name
            self.user.last_name = last_name

            # validate the password
            try:
                password_validation.validate_password(password, self.user)
                self.user.set_password(password)
            except ValidationError as error:
                self.add_error('password', error)
        return self.cleaned_data

    def save(self):
        self.user.is_active = True
        self.user.save()

        return self.user


class PasswordResetForm(forms.Form):
    phone_number = forms.CharField(
        label=_('Phone number'),
        widget=forms.TextInput(),
        validators=(User.phone_number_validator,),
    )

    @staticmethod
    def get_user(phone_number):
        user = UserModel.objects.filter(
            phone_number=phone_number,
            is_active=True
        ).first()

        if user is not None and user.has_usable_password():
            return user

    def clean(self):
        user = self.get_user(self.cleaned_data['phone_number'])

        if not user:
            self.add_error('phone_number', _('Any user with this phone number not found.'))
        else:
            self.cleaned_data['user'] = user
        return self.cleaned_data

    def save(self):
        user = self.cleaned_data['user']
        return user


class VerificationForm(forms.Form):
    otp_validator = RegexValidator(
        regex=r'^[0-9]{6}$',
        message=_('The verification code is invalid. Note that you use English numbers.'),
    )
    verification_code = forms.CharField(
        label=_('Verification code'),
        validators=(otp_validator,)
    )

    def __init__(self, identifier, *args, **kwargs):
        self.identifier = identifier
        super().__init__(*args, **kwargs)

    def clean_verification_code(self):
        verification_code = self.cleaned_data['verification_code']
        is_valid = otp.verify_code(self.identifier, verification_code)

        if not is_valid:
            self.add_error('verification_code', _('The verification code is invalid or expired.'))

        return verification_code

apps/dashboard/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import UpdateView, ListView


class ProfileView(LoginRequiredMixin, UpdateView):
    fields = (
        'first_name',
        'last_name',
    )
    template_name = 'dashboard/profile.html'
    success_url = reverse_lazy('dashboard:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request, _('Your information updated successfully.'))
        return super().form_valid(form)


class BookmarkListView(LoginRequiredMixin, ListView):
    template_name = 'dashboard/bookmark_list.html'

    def get_queryset(self):
        return self.request.user.bookmarks.prefetch_related('genres')


class DeviceListView(LoginRequiredMixin, ListView):
    template_name = 'dashboard/device_list.html'

    def get_queryset(self):
        return self.request.user.logged_in_devices.all()

templates/dashboard/_base.html
{% extends '_base.html' %}
{% load static %}

{% block meta_title %}داشبورد{% endblock %}

{% block css %}
  <link rel="stylesheet" href="{% static 'global/css/header.css' %}">
  <link rel="stylesheet" href="{% static 'dashboard/css/base.css' %}">
{% endblock %}

{% block content %}
  {% include 'includes/header.html' %}

  <main id="main" class="space-from-header">
    <div class="container pt-5" style="max-width: 900px">
      <div class="dashboard">
        {% include 'dashboard/includes/dashboard_navigation.html' %}
        {% block dashboard_content %}{% endblock dashboard_content %}
      </div>
    </div>
  </main>
{% endblock content %}

templates/dashboard/bookmark_list.html
{% extends 'dashboard/_base.html' %}
{% load static %}

{% block meta_title %}نشان شده‌ها{% endblock %}

{% block css %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'content/css/item.css' %}">
{% endblock %}

{% block dashboard_content %}
  <div class="content-box rounded p-md-3">
    <div class="py-3">
      <div class="row">
        {% for object in object_list %}
          <div class="col-6 col-sm-4 col-md-3 mb-3">
            {% include 'content/includes/item.html' with object=object %}
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

templates/dashboard/device_list.html
{% extends 'dashboard/_base.html' %}
{% load utils %}
{% load static %}

{% block meta_title %}دستگاه ها{% endblock %}

{% block css %}
  {{ block.super }}
  <style>
      .objects td {
          padding-top: 1rem;
          padding-bottom: 1rem;
      }
  </style>
{% endblock %}

{% block dashboard_content %}
  <section class="content-box p-2 rounded p-md-3">
    <p>حساب کاربری شما در دستگاه‌های زیر فعال است.</p>
    <div class="objects overflow-auto">
      <table class="table" style="white-space: nowrap">
        <thead>
        <tr>
          <th scope="col">دستگاه</th>
          <th scope="col">آخرین ورود</th>
          <th scope="col">آدرس ای پی</th>
          <th scope="col">عملیات</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
          <tr>
            <td>{{ object.device_name }}</td>
            <td>{{ object.last_login|jdate:'%H:%M:%S %Y/%m/%d' }}</td>
            <td>{{ object.ip_address }}</td>
            <td class="text-center">
              {% if object.session_key != request.session.session_key %}
                <button class="revoke-session btn btn-danger" data-session-key="{{ object.session_key }}">خروج</button>
              {% else %}
                -
              {% endif %}
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </section>
{% endblock dashboard_content %}

{% block js %}
  {{ block.super }}
  <script>
    $('.revoke-session').click((e) => {
      const sessionKey = $(e.currentTarget).data('session-key');

      $.ajax({
        url: `{% url 'users:revoke_session' %}?session_key=${sessionKey}`,
        method: 'delete',
        headers: {
          'X-CSRFToken': '{{ csrf_token }}',
        },
        success(res) {
          $(e.currentTarget).parents('tr').remove();
        },
        error(err) {
          ajaxErrorToast(err.status, 'خطایی هنگام خروج دستگاه از حساب کاربری به وجود آمد. لطفا بعدا امتحان کنید.');
        },
      });
    })
  </script>
{% endblock js %}

templates/dashboard/password_change_form.html
{% extends 'dashboard/_base.html' %}
{% load widget_tweaks %}

{% block css %}
  {{ block.super }}
  <style>
      .input-group ul {
          list-style: none;
          padding-right: .5rem;
          padding-top: .5rem;
          color: var(--bs-gray);
          font-size: .9rem;
      }

      ul.errorlist {
          color: var(--bs-danger);
          font-size: .9rem;
          list-style: none;
          padding: .2rem;
      }

      ul.errorlist.nonfield {
          padding: 0;
      }
  </style>
{% endblock %}

{% block dashboard_content %}
  <div class="content-box p-2 p-md-3 rounded profile-form">
    {% include 'includes/messages.html' with classes='text-center' %}
    <form method="post">
      {% csrf_token %}
      <div class="input-group d-flex flex-column mb-3">
        <label for="id_first_name" class="form-label">{{ form.old_password.label }}</label>
        {{ form.old_password|add_class:'n-input' }}
        {{ form.old_password.errors }}
      </div>
      <div class="input-group d-flex flex-column mb-3">
        <label for="id_last_name" class="form-label">{{ form.new_password1.label }}</label>
        {{ form.new_password1|add_class:'n-input' }}
        {{ form.new_password1.help_text }}
      </div>
      <div class="input-group d-flex flex-column mb-3">
        <label for="id_last_name" class="form-label">{{ form.new_password2.label }}</label>
        {{ form.new_password2|add_class:'n-input' }}
        {{ form.new_password2.errors }}
      </div>
      <button class="btn btn-primary w-100" type="submit">ذخیره</button>
    </form>
  </div>
{% endblock %}

templates/dashboard/profile.html
{% extends 'dashboard/_base.html' %}
{% load widget_tweaks %}

{% block dashboard_content %}
  <section class="p-2 p-md-3 rounded content-box subscription">
    <div class="row justify-content-between">
      {% if user.is_vip %}
        <div class="status col-8">
          <h5>وضعیت اشتراک</h5>
          <span class="d-block d-sm-inline">فعال تا تاریخ :</span>
          <span class="text-success">
            {{ user.vip_left.days }}
             روز مانده
          </span>
        </div>
        <div class="col-4 text-end align-self-center">
          <a href="{% url 'subscription:plans' %}" class="btn btn-primary">تمدید اشتراک</a></div>
      {% else %}
        <div class="status col-8">
          <h5>وضعیت اشتراک</h5>
          <span class="text-danger">شما اشتراک ندارید، برای تماشای فیلم‌ها اشتراک تهیه کنید.</span>
        </div>
        <div class="col-4 text-end align-self-center">
          <a href="{% url 'subscription:plans' %}" class="btn btn-primary">خرید اشتراک</a>
        </div>
      {% endif %}
    </div>
  </section>
  <div class="content-box p-2 p-md-3 rounded profile-form">
    {% include 'includes/messages.html' with classes='text-center' %}
    <form method="post">
      {% csrf_token %}
      <div class="input-group d-flex flex-column mb-3">
        <label for="id_first_name" class="form-label">نام</label>
        {{ form.first_name|add_class:'n-input' }}
        {{ form.first_name.errors }}
      </div>
      <div class="input-group d-flex flex-column mb-3">
        <label for="id_last_name" class="form-label">نام خانوادگی</label>
        {{ form.last_name|add_class:'n-input' }}
        {{ form.last_name.errors }}
      </div>
      <div class="input-group d-flex flex-column mb-3">
        <label for="id_password" class="form-label">
          گذرواژه
          <a href="{% url 'dashboard:password_change' %}" class="text-decoration-none">ویرایش</a>
        </label>
        <input type="password" class="n-input" id="id_password" value="**********" disabled>
      </div>
      <button class="btn btn-primary w-100" type="submit">ذخیره</button>
    </form>
  </div>
{% endblock %}